name: macOS 11 (out of support)
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v4
    - name: Setting the Environment Up.
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: source setup.sh "user" "User" "123456" "123456" "$NGROK_AUTH_TOKEN"
    - name: ngrok is now listening to VNC connections on...
      run: curl --silent http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'
    - name: enjoy free vps!
      run: sleep 21600
